[project]
name = "bacpipe"
version = "1.2.0"
description = "Use bacpipe to streamline the process of generating embeddings and analysing your PAM datasets."
readme = "README.md"
authors = [
    { name = "Vincent S. Kather", email = "vkather@gmail.com" }
]
requires-python = ">=3.11"

dependencies = [
    "apache-beam",
    "einops",
    "flax",
    "gdown",
    "httpx",
    "importlib-resources",
    "kagglehub",
    "keras-cv",
    "librosa",
    "ml-collections",
    "numba",
    "panel",
    "plotly",
    "pysocks",
    "pytest",
    "seaborn",
    "sounddevice",
    "streamlit",
    "tensorflow[and-cuda]",
    "tensorflow-hub",
    "tensorflow-io",
    "timm",
    "torch",
    "torchaudio",
    "torchcodec",
    "torchvision",
    "transformers",
    "umap-learn",
    "uvicorn",
    "uvloop; sys_platform != 'win32'",
    "zipp",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools.package-data]
"bacpipe" = ["*.yaml", "*.png"]


# Add this to include your package
packages = ["bacpipe"]

